server:
  port: 8002
spring:
  application:
    name: service-oss
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
aliyun:
  oss:
    file:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      keyid: LTAI5tE5joJZe2RWg6m4pKiZ
      keysecret: V6hg1rR8Doz7jprbJnBjqYKLTmZc51
      bucketname: guli-cjx